# Generated by Django 5.2.8 on 2025-11-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userfollowing_user_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('to_user', 'from_user')},
        ),
    ]
